services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - .:/usr/src/app/redis_data

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - grafana

  django:
    container_name: django
    build:
      context: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
      - grafana

volumes:
  grafana_storage:
  prometheus_data: