services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/redis_data

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - grafana

  django:
    container_name: django
    build:
      context: .
    volumes:
      - .:/usr/src/app/
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
      - grafana

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

volumes:
  grafana_storage:
  prometheus_data:
  static_volume:
  media_volume:
  redis_data:
